### ISSUE TITLE
Some Discord invitation links broken

### ISSUE THREAD

**Issue by villesundell** [MystenLabs/awesome-move#6]
Hello! These Discord invitation links seem to be expired:
* [Move Language Discord](https://discord.gg/kRDkxyEt)
* [Move @ Mysten Labs](https://discord.gg/yyYQcckG)
* [Move @ StarCoin](https://discord.gg/Sek9Cnxt)

The 0L one works, though.

**Comment by jolestar** [comment]
Starcoin discord link: https://discord.gg/starcoin
