### ISSUE TITLE
Inclusion to the "Awesomeverse"

### ISSUE THREAD

**Issue by villesundell** [MystenLabs/awesome-move#9]
Hello everyone!
Awesome lists are aggregated to the "main" [awesome](https://github.com/sindresorhus/awesome#readme) repository.
If included, `awesome-move` would be accessible from tools using the `awesome` repository, such as [Awesome Indexed](https://awesome-indexed.mathew-davies.co.uk/), [awesomelists.top](https://awesomelists.top), and [others](https://github.com/sindresorhus/awesome#related).

However, [inclusion requirements](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-awesome-list) are quite strict, but not impossible to meet.

I can work out most of the stuff (such as style, content, structure, etc.) and open a PR, but unfortunately there are a few things I can't do alone. Some of these are:
 * Changing license to Creative Commons (now would be the ideal time, since we have just a few contributors)
 * Repository topics (`awesome-list` & `awesome`)

I am opening this issue for general discussion on the idea of inclusion, and will link the PRs to this issue.

Feel free to close this issue if inclusion to the list is not desired :slightly_smiling_face:

**Comment by sblackshear** [comment]
Good idea + totally open to changing the license to creative commons!

I am less clear what the repository topics change would mean, but open to that as well.

**Comment by villesundell** [comment]
@sblackshear Great! :tada: The repository topics are listed below the repository description, and can be modified only by project admins. For example, https://github.com/diem/move/ has the following topics: "smart-contracts", "blockchain", "verification".
